# Generated by Django 3.0.6 on 2020-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='age',
            field=models.IntegerField(),
        ),
    ]
